name = "CorpusCleanerForTWLaws"
uuid = "32148328-147a-4c3a-aded-c727b77b4e74"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
